services:

  db:
    container_name: foodgram-db
    image: postgres:16.8
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_NAME}
    env_file: .env
    restart: always
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    container_name: foodgram-back
    build:
      context: ../backend
    env_file: .env
    restart: always
    volumes:
      - static_data:/app/static_data/
      - media_data:/app/media_data/
    depends_on:
      - db

  frontend:
    container_name: foodgram-front
    build: ../frontend
    volumes:
      - ../frontend/:/app/result_build/

  nginx:
    container_name: foodgram-proxy
    image: nginx:1.25.4-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_data:/static_data/
      - media_data:/media_data/
    depends_on:
      - backend

volumes:
  pg_data:
  static_data:
  media_data: